### ISSUE TITLE
DataCache accessors are not accessible anymore in Commerce SDK

### ISSUE THREAD

**Issue by emishura** [microsoft/Dynamics365Commerce.Solutions#137]
Hello,

Previously we could create our own CachceAccessors (inheriting from DataCacheAccessor). Now the DLL which contains this class is not accessible within Nuget packages. Please also expose the DataCacheAccessors so we can create our own accessors

Best regards,
Elena

**Comment by lukedgr** [comment]
Hi @emishura, thank you for reporting this issue. Unfortunately, we are not able to track extensibility requests through the GitHub page. If the CacheAccessors are still needed please file an extensibility request using the process documented below.

https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/extensibility-requests
