### ISSUE TITLE
Info Code Dialog auto close

### ISSUE THREAD

**Issue by prawind** [microsoft/Dynamics365Commerce.Solutions#143]
Hi,

We have an requirement where we need to close the Info code dialog automatically based on Scanning the ID\Passport for the  tobacco product where Info code has been configured in FO.

When we scan the item at POS, info code dialog pops up and we scan the ID\Passport to verify customer age and display the validation message to user based on PostGetReasonCodeLineTrigger. When i hit OK button on validation dialog, the info code dialog should close automatically and item should not be added to the cart.

Right now, we need to manually click Cancel button on Info code dialog to close it. please let me know any solution on this

**Comment by madyke** [comment]
Informed by support that this requested scenario is no longer needed.
