### ISSUE TITLE
POS extension package has failures (v10.0.32)

### ISSUE THREAD

**Issue by ax365** [microsoft/Dynamics365Commerce.Solutions#153]
There are <`14 success and 11 failures`> when **StoreCommerce** tries to load my extension package.

![image](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/138946791/0f5eef03-4451-47eb-ad35-29fa54678ce1)

Most of the error messages are of this same format. And it's not entirely clear what's exactly the issue:
_`Cannot read properties of undefined (reading 'moduleObj') Loading https://extensions.local.storecommerce.dynamics.com/Commerce.Extensions/Views/MyCustomView/MyCustomViewModel.js`_

Any idea what might be wrong?

**_Most recent update:_** After further investigation I've noticed that all [11] failures are for TypeScript extensions/classes that import/execute custom Typescript request classes (these requests are actually defined in the CRT but are used in TypeScript through the proxy generation). One of the custom "entities" that were created in CRT were extending an OOTB class. And this was causing an issue with the TypeScript proxy *.g.ts file generation. I didn't actually need this custom CRT class to be generated by the TypeScript proxy -- therefore, after excluding it from the proxy *.g.ts file generation, I was able to get this resolved.

---
I'm using a cloud-hosted developer VM with it's own instance of RetailServer and AxDB channel database with 9999 distribution job completed. 

I have the following [6] projects inside my CommerceSDK 
(I've used the nuget packages for some to convey which projects these are):
<`CRT project`>
<`POS extensions project`>
<`Database extensions project`>
<`Microsoft.Dynamics.Commerce.Sdk.ScaleUnit`>
<`Microsoft.Dynamics.Commerce.Sdk.Installers.ScaleUnit`>
<`Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce`>

I've setup the IIS-Hosted Local CSU on this cloud hosted VM.
---

**Comment by madyke** [comment]
Copying solution OP's solution here for visibility:

_Most recent update: After further investigation I've noticed that all [11] failures are for TypeScript extensions/classes that import/execute custom Typescript request classes (these requests are actually defined in the CRT but are used in TypeScript through the proxy generation). One of the custom "entities" that were created in CRT were extending an OOTB class. And this was causing an issue with the TypeScript proxy *.g.ts file generation. I didn't actually need this custom CRT class to be generated by the TypeScript proxy -- therefore, after excluding it from the proxy *.g.ts file generation, I was able to get this resolved._
