### ISSUE TITLE
Change POS Payment Button panel

### ISSUE THREAD

**Issue by LavanyaNiki** [microsoft/Dynamics365Commerce.Solutions#157]
I have requirement from customer that button grid for Payments will be hidden with a button grid containing only the Calculate button (custom button).

Once the user executes the Calculate button, the system will perform the actions related to that button and, at the end, the button grid corresponding to the Payments will be displayed. 

I have attempted to create Calculate button as Sub menu, however the Calculate button is unable to carry out both its associated activity and serve as a submenu.

Please help how to implement this requirement.

**Comment by madyke** [comment]
Handled this offline through an extension request, pasting workaround details here for visibility:

After looking through the customer’s scenario as you described and in the extensibility request, it seems like the actual business scenario they want to implement is to ensure that the third-party APIs for things like promos, discounts, and loyalty are always run prior to the cashier starting the payment process.

If that’s the case, then the customer should be able to accomplish this by using the PrePaymentTrigger. That trigger is always run before the payments process begins, so the customer should be able to create an extension that extends that class and make the calls to all the third-party APIs from within that extension. It also has the extra benefit of being run automatically without requiring any additional clicks that would slow down the payment process with the UI changes the customer suggested.

While we don’t have a sample for the PrePaymentTrigger specifically, we do have a sample for another Cancelable trigger, the [PreSetQuantityTrigger (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FDynamics365Commerce.InStore%2Fblob%2Frelease%2F9.46%2Fsrc%2FStoreCommerceSamples%2FExtend%2FTriggers%2FTriggerSamples%2FPos%2FConfirmChangeQuantityTrigger.ts&data=05%7C01%7CMatthew.Dyke%40microsoft.com%7C14d990956d554b3eec3708db9c929023%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638275925628118827%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CHW%2BZIF%2BpRqY%2BBsDbnHTRMmDfg5r9KFDB9eoR6ip%2FHo%3D&reserved=0). The customer should be able to use that as a guide for how to set up the PrePaymentTrigger.
