### ISSUE TITLE
Why does the creating a new app registration need a subscription level access for Self-Hosted Installation?

### ISSUE THREAD

**Issue by sudarshan-onactuate** [microsoft/Dynamics365Commerce.Solutions#163]
### Discussed in https://github.com/microsoft/Dynamics365Commerce.Solutions/discussions/162

<div type='discussions-op-text'>

<sup>Originally posted by **sudarshan-onactuate** August  1, 2023</sup>

 If it is mandatory to have subscription level access, then please help in the query below.

 

What resources does this app registration need to access so that we can create a custom role to enable appropriate access for the app registration on the subscription ?</div>

**Comment by Pikhulya** [comment]
Assuming you are talking about on-prem installers - none of them requires any kind of Subscription, assuming you are talking about Azure Subscription.

Please provide more details including detailed repro steps as well as error messages if any, the information provided now doesn't contain any specific reproducible details of the difficulties you are dealing with.

**Comment by Pikhulya** [comment]
Closing as there is no response.
