### ISSUE TITLE
StoreCommerceApp custom controls are not editable or visible after migration from MPOS RetailSDK

### ISSUE THREAD

**Issue by tutsinco** [microsoft/Dynamics365Commerce.Solutions#164]
Hello,

We've migrated POS extensions from Modern POS RetailSdk to StoreCommerce App CommerceSDK. In StoreCommerce we can see our custom controls. However, they are not edible, and if we generate the list of values, then we do not see these values on the form. We are using knouckout.js.

Example

Store commerce:
![image](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/57107514/6cf22e9f-d12d-41a0-b648-f65b15b00d52)

MPOS:
![image](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/57107514/cf9b5e97-d47d-4b32-b5e0-b8c70a5e2e5b)

Of course, we've implemented InitializeStationTrigger as in GasStation Example
![image](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/57107514/984c2100-7a04-4c1d-be95-62e5be61e75b)

Commerce SDK Component:
Component Version:
Commerce SDK Version: 9.45
Exception/Error Details:

**Comment by madyke** [comment]
@tutsinco - The team took a look at the extension code that was provided in the support ticket. The `toggleSwitch` data bind that is used for these custom controls is not supported, the `Toggle` control from Commerce SDK should be used instead. In general, POS does not support custom binding handlers, the fact that these worked in MPOS and Retail SDK was coincidental and not an officially supported feature.

These documents provide details on how customers can migrate to Commerce SDK and use the POS controls in extensions:
[Removal of the Pos.UI.Sdk library](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-extension/migrate-pos-extension#removal-of-the-posuisdk-library)
[Use POS controls in extensions](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-extension/controls-pos-extension)
