### ISSUE TITLE
Third party library knockout-postbox.js not getting load. 

### ISSUE THREAD

**Issue by ranesh84** [microsoft/Dynamics365Commerce.Solutions#165]
Hi,

We are experiencing knockout-postbox.js not getting load after upgrading commerce sdk, we are getting below error, can you please help us to guide. how we can fix this issue?

[/knockout-postbox.js](https://mg...../Libraries/knockout-postbox.js) ****detected as amd but didn't execute correctly. Instantiating**** [https://mgmri-](https://mg...../Libraries/)..../Libraries/knockout-postbox.js](https://mg......../Libraries/knockout-postbox.js)
****

**Comment by lukedgr** [comment]
Hi @ranesh84 , unfortunately we do not have enough information in the post above to help with this issue. We do support loading AMD module libraries from Store Commerce extensions as outlined in the doc linked below and have some examples shown in our InStore repo.

Docs: https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-extension/knockout-pos-extension
Sample using knockout: https://github.com/microsoft/Dynamics365Commerce.InStore/blob/release/9.47/src/StoreCommerceSamples/Solutions/GasStationSample/Pos/manifest.json
