### ISSUE TITLE
Fiscal Fields Missing on POS Receipts

### ISSUE THREAD

**Issue by fern-diaz** [microsoft/Dynamics365Commerce.Solutions#171]
### Summary
**Describe the issue**
After incorporating the CommerceSDK FiscalIntegration/EFRSample into our ScaleUnit build, we are unable to get the fiscal fields included in our POS receipts. This includes fiscal fields for Germany, Austria, and France.
Receipt formats, Language Text, and Custom Fields have all been set accordingly in HQ and proper syncs ran.

**Version Info**
Commerce SDK Version: 9.45

### Details
Using Germany as an example.
Steps have been followed using the **"Fiscal registration service integration sample for Germany"** document. (https://learn.microsoft.com/en-us/dynamics365/commerce/localizations/emea-deu-fi-sample)

After integrating the EFRSample, we are able to capture fiscal information in HQ as well as in the EFSTA fiscal plugin.
However, fiscal fields are missing from POS receipts.

When I look at the legacy/RetailSDK docs for Germany **"Deployment guidelines for the fiscal registration service integration sample for Germany (legacy)"** (https://learn.microsoft.com/en-us/dynamics365/commerce/localizations/emea-deu-fi-sample-sdk#production-environment)
I see a section on adding the **Microsoft.Dynamics.Commerce.Runtime.ReceiptsGermany** dll to the **commerceruntime.ext.config**.
<img width="901" alt="Screen Shot 2023-08-21 at 1 31 06 PM" src="https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/142841897/79df4a41-729b-411f-b4b5-dd31fa324b98">

This .dll looks to include a request handler that adds the fiscal fields to the POS receipts.
![Screen Shot 2023-08-21 at 1 32 51 PM](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/142841897/415b11db-fa9c-4e67-82c0-beafc8820693)

In CommerceSDK, when I build the ScaleUnit project the **commerceruntime.ext.config** that gets generated is below. 
Located at ScaleUnit\bin\Debug\netstandard2.0\CloudScaleUnitExtensionPackage\RetailServer\Code\bin\ext
![Screen Shot 2023-08-21 at 1 36 07 PM](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/142841897/7aa1b07c-edef-40e0-969f-9485b9426642)

Since this config file is generated on build, I cannot manually add the necessary .dll's (below) to it.
Microsoft.Dynamics.Commerce.Runtime.ReceiptsGermany
Microsoft.Dynamics.Commerce.Runtime.ReceiptsAustria
Microsoft.Dynamics.Commerce.Runtime.ReceiptsFrance

Should these automatically be included in CommerceSDK, or is there another way to add these via a project property/tag?
I can manually add these to the **commerceruntime.ext.config**  file and then re-zip the package, but is this the recommended approach? How will these be handled for pipelines?

Any advice is much appreciated. Thank you!

**Comment by lukedgr** [comment]
Hi @fern-diaz , in the Commerce SDK it is not required to include the country specific receipt assemblies in the commerceruntime.ext.config file. In the Commerce SDK the country specific receipt logic is already loaded by default in the Commerce Runtime.

Please refer to this document on how to configure the custom receipt fields for Germany. https://learn.microsoft.com/en-us/dynamics365/commerce/localizations/dev-itpro/emea-deu-fi-sample#configure-custom-fields-so-that-they-can-be-used-in-receipt-formats-for-sales-receipts
