### ISSUE TITLE
Unable to deploy lables/Resource DLL specific to different language during CSU package deployment and Store commerce package install

### ISSUE THREAD

**Issue by LavanyaNiki** [microsoft/Dynamics365Commerce.Solutions#174]
We use language-specific labels for creating receipts, and these labels are added as Resources (.resx) to the CRT project. What we have seen is that these folders are not included in the packages when Store Commerce and CSU are created. 
Both online and offline mode transactions need these files.

Online: The folders "CA-es" and "es" path "C:\RetailServer\WebRoot\bin\Ext" include labels.

Offline: The folder "C:\Program Files\Microsoft Dynamics 365\10.0\Store Commerce\Extensions\XXXXX\CommerceRuntime" has to include labels.

We need solution how to include label specific folder in the Store commerce installer package and Cloud Scale unit package.

**Comment by madyke** [comment]
Hello @LavanyaNiki - I'm not aware of any different requirements for resource labels, so I would think that the only thing that would need to be done in order to copy the folders to the Store Commerce and CSU packages would be to make sure they are included in the installer project files.

Can you try adding the following code to the `.StoreCommerce.Installer.csproj` and `.ScaleUnit.Installer.csproj` files in your extension, with a `<Content Include="">` element for each file you want to include:

```
 <ItemGroup>
    <Content Include="path_to_file_to_include">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

If these steps don't work, let me know and I can reach out to the localization team to see if there are any additional requirements for content like this.

**Comment by LavanyaNiki** [comment]
> Hello @LavanyaNiki - I'm not aware of any different requirements for resource labels, so I would think that the only thing that would need to be done in order to copy the folders to the Store Commerce and CSU packages would be to make sure they are included in the installer project files.
> 
> Can you try adding the following code to the `.StoreCommerce.Installer.csproj` and `.ScaleUnit.Installer.csproj` files in your extension, with a `<Content Include="">` element for each file you want to include:
> 
> ```
>  <ItemGroup>
>     <Content Include="path_to_file_to_include">
>       <CopyToOutputDirectory>Always</CopyToOutputDirectory>
>     </Content>
>   </ItemGroup>
> ```
> 
> If these steps don't work, let me know and I can reach out to the localization team to see if there are any additional requirements for content like this.

Hello @madyke: Thank you for the suggestion, tried implement the solution but it's not working.

**Comment by LavanyaNiki** [comment]
Hello @madyke: Thank you for the suggestion, tried implement the solution but it's not working.

**Comment by lukedgr** [comment]
@LavanyaNiki , please add the snippets below to the Scale Unit and Store Commerce Installer csproj files to include the resources.

ScaleUnit.csproj

    <Target Name="CopyResourceFilesInPackage" BeforeTargets="ReplaceCustomManifestMetadata">
      <ItemGroup>
        <ResourceFileAssemblies Include="..\CommerceRuntime\bin\$(Configuration)\$(TargetFramework)\**\Contoso.EFRSample.CommerceRuntime.resources.dll" />
      </ItemGroup>
      <Copy SourceFiles="@(ResourceFileAssemblies)" DestinationFolder="$(OutputPath)$(ScaleUnitPackageName)\RetailServer\Code\bin\ext\%(ResourceFileAssemblies.RecursiveDir)" />
    </Target>

StoreCommerce.Installer.csproj

`  <Target Name="LinkResourceFilesInPackage" BeforeTargets="RetailInstallerFrameworkCopyFilesToIntermediateOutputPath" DependsOnTargets="PrepareProjectReferences;Compile;">
    <ItemGroup>
      <_ResourceFileAssemblies Include="..\CommerceRuntime\bin\$(Configuration)\netstandard2.0\**\Contoso.EFRSample.CommerceRuntime.resources.dll" />
    </ItemGroup>
    <PropertyGroup>
      <CommerceRuntimeExtensionsDirectoryName Condition="'$(CommerceRuntimeExtensionsDirectoryName)' == ''">CommerceRuntime</CommerceRuntimeExtensionsDirectoryName>
    </PropertyGroup>
    <ItemGroup>
      <ZipFiles Include="@(_ResourceFileAssemblies->'%(FullPath)')">
        <Link>$(CommerceRuntimeExtensionsDirectoryName)\%(_ResourceFileAssemblies.RecursiveDir)%(_ResourceFileAssemblies.Filename)%(_ResourceFileAssemblies.Extension)</Link>
      </ZipFiles>
    </ItemGroup>
  </Target>`

**Comment by LavanyaNiki** [comment]
Hello [lukedgr](https://github.com/lukedgr):  We have updated our Store commerce installer project with the snippet below. Following this, the installer was not generated correctly, and the project was not building completely. PFB error details.

8>C:\Users\lavanya.nagaraju\.nuget\packages\microsoft.dynamics.commerce.sdk.installers.storecommerce\9.46.23297.3\build\Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce.targets(159,5): error :
8>C:\Users\lavanya.nagaraju\.nuget\packages\microsoft.dynamics.commerce.sdk.installers.storecommerce\9.46.23297.3\build\Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce.targets(159,5): error : Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.IO.Abstractions, Version=14.0.0.0, Culture=neutral, PublicKeyToken=96bf224d23c43e59' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
8>C:\Users\lavanya.nagaraju\.nuget\packages\microsoft.dynamics.commerce.sdk.installers.storecommerce\9.46.23297.3\build\Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce.targets(159,5): error :    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
8>C:\Users\lavanya.nagaraju\.nuget\packages\microsoft.dynamics.commerce.sdk.installers.storecommerce\9.46.23297.3\build\Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce.targets(159,5): error :    at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
8>C:\Users\lavanya.nagaraju\.nuget\packages\microsoft.dynamics.commerce.sdk.installers.storecommerce\9.46.23297.3\build\Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce.targets(159,5): error :    at System.Reflection.RuntimeMethodInfo.GetParameters()
8>C:\Users\lavanya.nagaraju\.nuget\packages\microsoft.dynamics.commerce.sdk.installers.storecommerce\9.46.23297.3\build\Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce.targets(159,5): error :    at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
8>C:\Users\lavanya.nagaraju\.nuget\packages\microsoft.dynamics.commerce.sdk.installers.storecommerce\9.46.23297.3\build\Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce.targets(159,5): error :    at System.Exception.GetStackTrace(Boolean needFileInfo)
8>C:\Users\lavanya.nagaraju\.nuget\packages\microsoft.dynamics.commerce.sdk.installers.storecommerce\9.46.23297.3\build\Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce.targets(159,5): error :    at System.IO.FileLoadException.ToString()
8>C:\Users\lavanya.nagaraju\.nuget\packages\microsoft.dynamics.commerce.sdk.installers.storecommerce\9.46.23297.3\build\Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce.targets(159,5): error :    at Microsoft.Dynamics.Commerce.Installers.Framework.Program.Main() in C:\Users\lavanya.nagaraju\.nuget\packages\microsoft.dynamics.commerce.sdk.installers.storecommerce\9.46.23297.3\contentFiles\cs\netstandard2.0\Program.cs:line 44
8>C:\Users\lavanya.nagaraju\.nuget\packages\microsoft.dynamics.commerce.sdk.installers.storecommerce\9.46.23297.3\build\Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce.targets(159,5): error MSB3073: The command "powershell.exe -NonInteractive -Command "& { C:\Users\lavanya.nagaraju\source\Commerce\CommerceSDK\src\StoreCommerce.Installer\bin\Debug\net472\\Tendam.StoreCommerce.Installer.exe install --skipversioncheck=true }"" exited with code -1.
8>Done building project "Tendam.StoreCommerce.Installer.csproj" -- FAILED.

The installer package that is generated is incorrect; during installation, we encountered the following errors.
<img width="932" alt="image" src="https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/140384016/5e46a99d-2932-4bb9-ba19-c652f313c440">

**Comment by shuelsmeier** [comment]
Hello @lukedgr, @madyke: I have updated the project file of my OnPrem Scale Unit Installer with the following snippet:

```xml
<Target Name="LinkResourceFilesInPackage" BeforeTargets="RetailInstallerFrameworkCopyFilesToIntermediateOutputPath" DependsOnTargets="PrepareProjectReferences;ValidateProjectConfiguration;Compile;">
  <ItemGroup>
    <_ResourceFileAssemblies Include="..\CommerceRuntime\bin\$(Configuration)\net6.0\**\Contoso.EFRSample.CommerceRuntime.resources.dll" />
  </ItemGroup>
  <ItemGroup>
    <ZipFiles Include="@(_ResourceFileAssemblies->'%(FullPath)')">
      <Link>%(_ResourceFileAssemblies.RecursiveDir)%(_ResourceFileAssemblies.Filename)%(_ResourceFileAssemblies.Extension)</Link>
    </ZipFiles>
  </ItemGroup>
</Target>
```

Running the installer results in the same error as above. Somehow the binding redirects are missing.

```txt
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.IO.Abstractions, Version=14.0.0.0, Culture=neutral, PublicKeyToken=96bf224d23c43e59' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
  at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
  at System.Reflection.RuntimeMethodInfo.GetParameters()
  at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
  at System.Exception.GetStackTrace(Boolean needFileInfo)
  at System.IO.FileLoadException.ToString()
  at Microsoft.Dynamics.Commerce.Installers.Framework.Program.Main() in C:\Users\shuelsmeier\.nuget\packages\microsoft.dynamics.commerce.sdk.installers.scaleunit\9.47.24058.3\contentFiles\cs\netstandard2.0\Program.cs:line 44
The command "powershell.exe -NonInteractive -Command "& { C:\xxxxxxxxxxx\Contoso.ScaleUnit.OnPrem.Installer\bin\Debug\net472\Contoso.ScaleUnit.OnPrem.Installer.exe install --skipversioncheck=true }"" exited with code -1.
```
