### ISSUE TITLE
InventoryAvailabilityServiceDataRetriever class is not availble.

### ISSUE THREAD

**Issue by ManishRetailDev** [microsoft/Dynamics365Commerce.Solutions#180]
### Discussed in https://github.com/microsoft/Dynamics365Commerce.Solutions/discussions/179

<div type='discussions-op-text'>

<sup>Originally posted by **ManishRetailDev** September  3, 2023</sup>
We are using this class in our legacy retailsdk code for getting the unposted quantities but in commerce sdk this class is not available. Is there any way that we can get the same functionality with any other class libaray. is there any alternate for this. </div>

**Comment by rickwyang** [comment]
We evaluated the impact of Commerce SDK and InventoryAvailabilityServiceDataRetriever.GetUnpostedQuantities is the one cannot be accessed. There will be a new extensibility point provided, please subscribe the change in this hotfix: 
https://fix.lcs.dynamics.com/Issue/Details?bugId=842077&dbType=3&qc=b0b6988e8fc964f29aa8ed82568805714ca6c8ac03c42bae42db0708e304a932
