### ISSUE TITLE
POS Build Errors (MPOS-Retail SDK project Migration to GitHub InStore StoreCommercePackagingSample)

### ISSUE THREAD

**Issue by Riaz-Dynamics365FOAndCommerce** [microsoft/Dynamics365Commerce.Solutions#209]
Currently there are 3 types of error. File with screenshots has been attached. Kindly provide Your kind understanding error by error.
[list of errors.docx](https://github.com/microsoft/Dynamics365Commerce.Solutions/files/13202099/list.of.errors.docx)

**Comment by dimontei** [comment]
I helped @Riaz-Dynamics365FOAndCommerce in the migration POS errors, in a created support case scope.
