### ISSUE TITLE
[Build Issue]CommerceRuntime Fiscal Integration depends on deprecated package.

### ISSUE THREAD

**Issue by ahgamal-ms** [microsoft/Dynamics365Commerce.Solutions#211]
Commerce SDK Version: .47

### Summary
Customer is using the FiscalIntegration project for EFRSample
https://github.com/microsoft/Dynamics365Commerce.Solutions/tree/release/9.48/src/FiscalIntegration/EFRSample

customer need to call  azure apis so they have add a reference for Azure.Storage.blobs but after that the project fails to compile using VS 2017.
customer has found that  "CommerceRuntime Fiscal Integration Document Provider Core library for Retail component" requires "Microsoft.Dynamics.Commerce.Diagnostics" that depends on the following deprecated assemblies:
* Microsoft.Extensions.DependencyInjection (1.1.1)
* Microsoft.Extensions.Logging (1.1.2)
* Microsoft.Extensions.Logging.Abstractions (1.1.2)
* Microsoft.Extensions.Logging.Debug (1.1.2)

now the project has duplicate versions of the same assembly , newer one from (azure.storage.blobs) and deprecated one from Core library for Retail component.
to overcome this customer has change the reference for (azure.storage.blobs) to (microsoft.azure.blob.storage) which is deprecated as well. it did compile now but it puts our extensions at risk (deprecated versions don't get hotfixes).
Please upgrade "Microsoft.Dynamics.Commerce.Diagnostics" dependencies to the supported versions.

Additionally customer tries to compile the project on VS 2019 with the reference to (azure.storage.blobs) and it did compile and the issue did not appear, but they are worried if they will face an issue with deployment for scale unit and whether if this deprecated reference should be addressed.

Visual Studio/Visual Studio Code/MSBuild Version: vs 2017

Does this happen every time the solution is built: yes

Name of Project with Error:
FiscalIntegration project for EFRSample
https://github.com/microsoft/Dynamics365Commerce.Solutions/tree/release/9.48/src/FiscalIntegration/EFRSample

MSBuild Error:

![image](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/74003164/f185be0e-fda1-4406-9f2e-b5f9000ae5e3)

![image](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/74003164/313fb2f7-da8e-434b-bac4-7884953e8d4d)

![image](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/74003164/2fe8db41-32cb-4e1f-8560-206054a72ece)

**Comment by madyke** [comment]
Hi @ahgamal-ms - unfortunately we no longer support development on Visual Studio 2017, and we recommend customers upgrade to a newer version. If the solution compiles without any issues on VS 2019, then they should be safe to use for deployment.
