### ISSUE TITLE
StoreCommerce sample project fails to build for 9.47

### ISSUE THREAD

**Issue by rphillipsnwt** [microsoft/Dynamics365Commerce.Solutions#214]
### Summary

Today my 9.47 StoreCommerce project, specifically the installer sub-project, started throwing an error during build. I switched over to the StoreCommerce sample project and received the same error during build. This error did not occur yesterday.

**Version and Error Info**

Commerce SDK Version: [9.47](https://github.com/microsoft/Dynamics365Commerce.InStore/tree/release/9.47)

Visual Studio/Visual Studio Code/MSBuild Version: Visual Studio Version: 16.11.26 / MSBuild Version: 16.11.2.50704

Does this happen every time the solution is built: Yes

Name of Project with Error: [StoreCommerce.Installer](https://github.com/microsoft/Dynamics365Commerce.InStore/tree/release/9.47/src/PackagingSamples/StoreCommerceApp/StoreCommerce.Installer)

MSBuild Error:
```
>C:\...\src\PackagingSamples\StoreCommerceApp\StoreCommerce.Installer\obj\Debug\net472\NuGet\A475414C3F7139320316876D3077ADF4A5DB0DEE\Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce\9.47.23312.7\Setup.cs(30,89,30,124): error CS0103: The name 'StoreCommerceExtensionInstallAction' does not exist in the current context
>C:\...\src\PackagingSamples\StoreCommerceApp\StoreCommerce.Installer\obj\Debug\net472\NuGet\A475414C3F7139320316876D3077ADF4A5DB0DEE\Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce\9.47.23312.7\Setup.cs(72,24,72,59): error CS0246: The type or namespace name 'StoreCommerceExtensionInstallAction' could not be found (are you missing a using directive or an assembly reference?)
```

### Reproducing the Issue

1. Clone the InStore sample and switch to the [release/9.47 branch](https://github.com/microsoft/Dynamics365Commerce.InStore/tree/release/9.47)
2. Load the [StoreCommerce sample solution](https://github.com/microsoft/Dynamics365Commerce.InStore/tree/release/9.47/src/PackagingSamples/StoreCommerceApp) into VisualStudio
3. Build

**Comment by Daniel-Guenter** [comment]
Yes that is happening for us now too. 
The issue is somewhere between version 9.47.23312.4 and 9.47.23312.7

**Comment by muniyaraj03** [comment]
Yes that is happening suddenly now for us. it was working till yesterday. 
Any update on this issue.

**Comment by Ahmedbreaka** [comment]
yes this happened to us now when upgraded to [release/9.47 branch](https://github.com/microsoft/Dynamics365Commerce.InStore/tree/release/9.47)

**Comment by cpfordham** [comment]
Has MS started looking into this issue? This is significant for our deployment.

**Comment by Vekto** [comment]
Still exists in 9.47.23313.4. we have gotten around this by locking our projects to an earlier version for the time being.
```
<ItemGroup>
    <PackageReference Include="Microsoft.Dynamics.Commerce.Sdk.Installers.StoreCommerce" Version="[9.47.23312.4]" />
</ItemGroup>
```

**Comment by madyke** [comment]
Hi folks, we have opened an internal bug and are actively investigating. In the meantime, you can unblock yourselves by locking the project reference to a working build, as @Vekto has shown above.

**Comment by madyke** [comment]
Hello everyone, we have identified the issue and are working on a fix

**Comment by MHaseebAnjum** [comment]
Hi,
Did someone get the fix of this issue?

**Comment by madyke** [comment]
Hi everyone,

This has been fixed, and the new builds have just been released. The issue is resolved on these builds and later:
- 9.47.23317.7
- 9.48.23317.6

Thanks everyone for reporting the issue, we're working on adding a new test suite to the Samples repo so these issues will be detected and prevented in the future.

**Comment by rphillipsnwt** [comment]
Thanks @madyke!
