### ISSUE TITLE
Store Commerce Offline Mode Custom CRT call not working (Can't find manager)

### ISSUE THREAD

**Issue by LavanyaNiki** [microsoft/Dynamics365Commerce.Solutions#220]
We are using 9.47 version commerce SDK and when we switch to Offline mode all extensions are throwing an error. 

Exception: Retail proxy client offline request failed. RequestUri: crt://offline/AVARetailParametersEntityManager/GetAVARetailParameters?queryResultSettings=SCRUBBED&sellerId=SCRUBBED&$locale=SCRUBBED. Exception: System.InvalidOperationException: Can't find manager (AVARetailParametersEntityManager) with method (GetAVARetailParameters) with parameter count (2)
   at Microsoft.Dynamics.Commerce.RetailProxy.Adapters.AdaptorCaller.CallCommerceRuntimeAsync(String allInOneUrlString)
   at Microsoft.Dynamics.Commerce.RetailProxy.Adapters.AdaptorCaller.ExecuteAsync(String allInOneUrl).

Retail proxy extension manager method (managerName: AVARetailParametersEntityManager, methodName: GetAVARetailParameters, parameterCount: 2) is not found in any proxy extension assembly under *.Adapters namespace. The proxy call failed for crtUri: crt://offline/AVARetailParametersEntityManager/GetAVARetailParameters?queryResultSettings=SCRUBBED&sellerId=SCRUBBED&$locale=SCRUBBED.

This issue started post upgrade to 10.37. Now all the CRT side customizations causing this problem.

As per below blog Retail Server extension built using the Microsoft.Dynamics.Commerce.Runtime.Hosting.Contracts API can be used in and offline implementation, no need to generate separate C# proxy library.

https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/typescript-proxy-retail-pos

**Comment by Faycel44** [comment]
Hello did you find the answer ? I have the same error :( 

Even this thread does not help 
https://github.com/microsoft/Dynamics365Commerce.Solutions/issues/74

**Comment by LavanyaNiki** [comment]
@Faycel44
 It was due to a FileLoadException caused by incompatible versions of referenced libraries. To mitigate this issue, you need to ensure that the versions of the referenced libraries in your extension project match the versions used in the Commerce Scale Unit. You can find the correct versions in the repo.props file. 

Another way to check the used version is to directly find it in the installed Scale Unit by going to the Retail Server bin folder and checking the file properties.  Match the versions of the referenced libraries
