### ISSUE TITLE
Google map not loading on Store locator page in D365 eCommerce.

### ISSUE THREAD

**Issue by ddaytechnologies** [microsoft/Dynamics365Commerce.Solutions#225]
This is regarding D365 eCommerce.
We have done enchantment on store locator page and added google map. google map not rendering on website.

Thank you!

![GoogleMapError](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/153101831/b2ac01df-ec19-4916-9fab-68b8b8150794)

**Comment by bradyd** [comment]
This issue has been resolved here: https://github.com/microsoft/Msdyn365.Commerce.Online/issues/68
