### ISSUE TITLE
Getting customer_data threw exception error while trying to print customer details table in E-commerce page

### ISSUE THREAD

**Issue by PratikSuthar8** [microsoft/Dynamics365Commerce.Solutions#234]
### Summary
**Describe the issue**
i'm trying to print a table that contains the information of the customer in my e-commerce **Customer Data module**  but instad of getting the table i'm facing the bellow issue shown in the screenshot

### Screenshots
![Screenshot 2024-01-16 113845](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/136822147/9e0ebbd3-0888-47a9-8ea5-a2c96ba830cd)

**Comment by anastasiiaandreichuk** [comment]
Hi @PratikSuthar8 

Looks like `customer-data` is your custom module.
At line 18 in `customer.data.view.tsx` you're trying to read `someVarible.result` when `someVarible` is undefined. You can either check that `someVarible` is defined in an if statement, or use optional chaining (`someVarible?.result`).

Please note that we don't debug customer code.
