### ISSUE TITLE
Hardware Station Error in Commerce SDK for Store Commerce

### ISSUE THREAD

**Issue by Tech-Kishan** [microsoft/Dynamics365Commerce.Solutions#312]
### Summary
**Describe the issue**
I have migrated from Retail SDK to Commerce SDK and have a Hardware station component for check scanning process for payment method, when we hit check payment method for transaction it will invoke the scanner and scan the check to get the check details and finish the transaction after hitting the tender command in store commerce app, but when doing this the request for hardware station is not going through and giving hardware station related errors which is shown in screen shots. Also one more thing to note is that we are using third party Scanner to scan check which is **RDM** and they have provided the .dll for hardware station and a driver to install also this device uses Plug and play interface (USB) to connect to the Retail SDK (MPOS) and Commerce SDK (Store Commerce). 

**Version and Error Info**
Commerce SDK Component: Hardware Station
Commerce SDK Version:9.47.0.0
Exception/Error Details: Hardware station not accepting request to scan check.

### Screenshots

**Code From where it is sending request to Hardware Station :**
<img width="842" alt="image" src="https://github.com/user-attachments/assets/93478ac1-1ca8-4fca-9a45-ea3df782f641">

**Code From Hardware station Controller File :**
<img width="909" alt="image" src="https://github.com/user-attachments/assets/2c452de7-a0ae-4940-9ca8-1f6a08ffbe1c">
<img width="910" alt="image" src="https://github.com/user-attachments/assets/8fc39367-73ac-484c-b786-020649569230">
<img width="908" alt="image" src="https://github.com/user-attachments/assets/5f09a491-5716-4095-b4ae-b8fb91ba8ede">

**Error Messages :**

WebView event: extensibilityFrameworkExecuteRuntimeRequestFailed

POS runtime request of type 'HardwareStationDeviceActionRequest' for extension in package 'ERS.MICRCheckScanner' failed. Error Message: ["{\"stack\":\"CommerceError\\n    at new CommerceError (https://local.storecommerce.dynamics.com/Commerce.TypescriptUtilities.js:543:36)\\n    at ErrorParser.parseHardwareStationErrorMessage (https://local.storecommerce.dynamics.com/Pos.Peripherals.js:3078:47)\\n    at HardwareStationRequestHandler._onHardwareStationError (https://local.storecommerce.dynamics.com/Pos.Peripherals.js:1758:62)\\n    at reject_1 (https://local.storecommerce.dynamics.com/Pos.Peripherals.js:1695:69)\\n    at https://local.storecommerce.dynamics.com/Pos.Peripherals.js:1709:29\\n    at wrapper (https://local.storecommerce.dynamics.com/Commerce.AsyncResult.js:188:21)\",\"message\":\"\",\"name\":\"CommerceError\",\"_errorCode\":\"string_4914\",\"_title\":\"\",\"_handled\":false,\"errorCode\":\"string_4914\",\"title\":\"\",\"handled\":false}"]

{
  "requestType": "HardwareStationDeviceActionRequest",
  "packageName": "ERS.MICRCheckScanner",
  "packagePublisher": "ERS",
  "packageVersion": "1.0.0",
  "errorMessage": "[\"{\\\"stack\\\":\\\"CommerceError\\\\n    at new CommerceError (https://local.storecommerce.dynamics.com/Commerce.TypescriptUtilities.js:543:36)\\\\n    at ErrorParser.parseHardwareStationErrorMessage (https://local.storecommerce.dynamics.com/Pos.Peripherals.js:3078:47)\\\\n    at HardwareStationRequestHandler._onHardwareStationError (https://local.storecommerce.dynamics.com/Pos.Peripherals.js:1758:62)\\\\n    at reject_1 (https://local.storecommerce.dynamics.com/Pos.Peripherals.js:1695:69)\\\\n    at https://local.storecommerce.dynamics.com/Pos.Peripherals.js:1709:29\\\\n    at wrapper (https://local.storecommerce.dynamics.com/Commerce.AsyncResult.js:188:21)\\\",\\\"message\\\":\\\"\\\",\\\"name\\\":\\\"CommerceError\\\",\\\"_errorCode\\\":\\\"string_4914\\\",\\\"_title\\\":\\\"\\\",\\\"_handled\\\":false,\\\"errorCode\\\":\\\"string_4914\\\",\\\"title\\\":\\\"\\\",\\\"handled\\\":false}\"]",
  "correlationId": "ebc0a814-fc58-0d42-d3b1-fb31f9b767cb"
}

WebView event: remoteTaskManagerRunOutgoingTaskTimedOut
Outgoing task timed out. Correlation ID: 466fcfdc-65be-8b18-ee26-f2855b745950, Task name: HardwareStationWebViewRequest, Outgoing task id: a3126aae-3a3e-a46c-cf24-13da6aa718f6, TimeoutInMilliseconds: 120000, Serialized Parameters: {"action":"POST","targetHardwareStationRequestUri":"IPC://LOCALHOST/MICRCHECKSCANNER/CheckScanningProcess","requestBody":"true","requestLocale":"en-us","hardwareStationHeaders":[{"name":"Accept-Language","value":"en-us"},{"name":"ActivityId","value":"466fcfdc-65be-8b18-ee26-f2855b745950"}]}
{
  "correlationId": "466fcfdc-65be-8b18-ee26-f2855b745950",
  "taskName": "HardwareStationWebViewRequest",
  "outgoingTaskId": "a3126aae-3a3e-a46c-cf24-13da6aa718f6",
  "timeoutInMilliseconds": 120000,
  "serializedParameters": "{\"action\":\"POST\",\"targetHardwareStationRequestUri\":\"IPC://LOCALHOST/MICRCHECKSCANNER/CheckScanningProcess\",\"requestBody\":\"true\",\"requestLocale\":\"en-us\",\"hardwareStationHeaders\":[{\"name\":\"Accept-Language\",\"value\":\"en-us\"},{\"name\":\"ActivityId\",\"value\":\"466fcfdc-65be-8b18-ee26-f2855b745950\"}]}"
}

<img width="385" alt="image" src="https://github.com/user-attachments/assets/34a90591-4df1-434e-921a-838d1423c425">

<img width="480" alt="image" src="https://github.com/user-attachments/assets/47a0177b-99fe-48d0-8eb6-94a45adf8f78">
 
<img width="960" alt="image" src="https://github.com/user-attachments/assets/5c7764f6-32e8-401f-aaae-1c7a314cb795">

**Comment by jalaliskandar** [comment]
did you solve the issue?

**Comment by Tech-Kishan** [comment]
> did you solve the issue?

Still not solved

**Comment by Tech-Kishan** [comment]
Found a new clue, that there is a problem with the binding and because of that it is not working as we want 

These are the Retail SDK Code binding from HTML and Ts file
![image (10)](https://github.com/user-attachments/assets/4cc9579a-57ac-46fa-89a2-a15359dc969d)
![image (8)](https://github.com/user-attachments/assets/4e1d71c8-b5de-42e2-ad0e-58f0858e6810)
![image (7)](https://github.com/user-attachments/assets/ec68d9d2-42ef-4c80-a005-d803a47f9d1b)
![image (6)](https://github.com/user-attachments/assets/4343d507-0dc5-41ae-b88b-4d900cf8f9a0)
![image (5)](https://github.com/user-attachments/assets/fb2f5e02-be41-4d6a-8ee1-a9b784a715d5)

And these are the Commerce SDK code that had been done as the Microsoft GitHub repo for Commerce SDK suggest
![image (4)](https://github.com/user-attachments/assets/ba8ca600-4177-4771-a347-72bcd1a70b46)
![image (3)](https://github.com/user-attachments/assets/2b4b625e-0bc7-49e4-a6e0-acc3dab9b49f)
![image (2)](https://github.com/user-attachments/assets/46929599-dcef-4c45-932b-a022ec043326)
![image (1)](https://github.com/user-attachments/assets/ddc3c810-689b-4f2b-ace0-f84268163720)

**Comment by Tech-Kishan** [comment]
Issue Solved by me personally after just changing some architecture of code in HW controller file that solved the issue
