### ISSUE TITLE
Upgrade Commerce SDK solution to Net 6.0 which will support System.drawing.common

### ISSUE THREAD

**Issue by pruthvigowda483** [microsoft/Dynamics365Commerce.Solutions#325]
We are working on a customization where we need to use System.Drawing.Common, but unfortunately, it is not supported in .NET Standard 2.0. We tried using the System.Drawing.Common NuGet package on another platform, .NET 6.0, where it worked fine. Therefore, we attempted to upgrade our Commerce SDK to .NET 6.0.

However, the Store Commerce installer and Scale Unit installer projects are not building and are not generating .exe files. Currently, the Store Commerce and Scale Unit projects are in .NET Framework 4.7.2, which is building successfully and generating the .exe file needed for installation. But when we convert these projects to .NET 6.0, they fail to build.

Can anyone help address this issue?

**Comment by lukedgr** [comment]
@pruthvigowda483 - the installer projects cannot be converted to .NET 6. They should remain as .NET Framework 4.7.2 even while the CommerceRuntime assemblies are targeting .NET 6. Please see the below sample solution that has the same setup that is working.

The important aspect is adding: ReferenceOutputAssembly="false" on the project reference in the installer project.

https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/blob/release/9.51/src/ScaleUnitSample/Installer/ScaleUnit.Sample.Installer.csproj
