### ISSUE TITLE
Debug the Commerce SDK InStore Sample

### ISSUE THREAD

**Issue by pruthvigowda483** [microsoft/Dynamics365Commerce.Solutions#43]
Hi Team,

I am migrating the Retail SDK to Commerce SDK where i have taken InStore sample - > store commerce APP but i cannot debug the POS solution in visual studio 2017 how we can debug the POS solution can anyone guide me?
Note:- i want to debug store commerce APP POS extensions in visual studio 2017

Thanks in advance

**Comment by madyke** [comment]
Hello @pruthvigowda483 - unfortunately, Visual Studio 2017 is no longer supported for Store Commerce development. Please upgrade to Visual 2022 or use Visual Studio Code for development purposes.
