### ISSUE TITLE
CRT: NuGet packaging issue

### ISSUE THREAD

**Issue by onikolaiev** [microsoft/Dynamics365Commerce.Solutions#55]
The NuGet package generated from the CRT project doesn`t contain the SQL files from the ChannelDatabase project.
How to generate a NuGet package that contains the schema changes?
![image](https://user-images.githubusercontent.com/10218336/236815398-7dba9596-5c41-4f2f-9172-2405742956ea.png)

**Comment by lukedgr** [comment]
Hi @onikolaiev , there should be a separate "ScaleUnit" project that references both the CRT and ChannelDatabase project like we have in the scale unit samples [here](https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/blob/release/9.45/src/ScaleUnitSample/ScaleUnit/ScaleUnit.csproj). To generate a NuGet package for your Scale Unit solution please set the "GeneratePackageOnBuild" property to true on the scale unit project. The package generated from this project type should include the SQL scripts, CRT assemblies, and POS extensions (if any).
