### ISSUE TITLE
SaveExtensionPropertiesOnCartLines request can apply to wrong line

### ISSUE THREAD

**Issue by Vekto** [microsoft/Dynamics365Commerce.Solutions#57]
We're trying to update extension properties on lines. Using the SaveExtensionPropertiesOnCartLines is resulting in extension properties being on the wrong line.

`SaveExtensionPropertiesOnCartLinesClientRequestHandler.prototype._saveExtensionPropertiesOnCartLines`

In this method the LineId is used to filter the lines returning an un-ordered set of cartLines, then the extension properties are applied based just on index. For us this result's in assigning extension properties to the incorrect lines when our save request doesn't align with the ordering.

**Comment by madyke** [comment]
Thank you for reporting this, we have filed an internal bug for our team to update the logic here so that the save request matches the returned set of cartLines with the updated properties based on the line ID. The fix will be released in a future update.
