### ISSUE TITLE
Looking for a post-load hook in Custom Views

### ISSUE THREAD

**Issue by Vekto** [microsoft/Dynamics365Commerce.Solutions#59]
Submitted extension request: #793036

Result was a recommendation to raise the discussion here.

We're looking for a way to have code execute after a view has created it's controls (dataList, command button). So for instance, we wanted to replicate the form validation in base product which is done with a custom binding handler on the command buttons. Unfortunately the included extension point OnReady in the view happens before any of the base controls are generated. So we cannot query out the command button to add custom binding handlers to it.

A similar situation right now is I would like to apply custom CSS classes to a dataList row for some highlighting but same issue, the items are not generated until afterwards.

One thing I can do is asynchronously add the binding and assume it will be later in async queue then the generation (seemed to work for the command button) but I'd rather no rely on that.

Thanks

**Comment by lukedgr** [comment]
Hi @Vekto , the onShown function is the best place to handle this type of logic. There is a chance that it will still be executed prior to all the controls being bound though so it is best to check that the elements exist before attempting to modify them. If they don't exist you could then schedule a timer to check again in 500 ms, and repeat that process until you're able to update all the elements as needed. The doc below describes the lifecycle methods available in custom views.

https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-extension/custom-pos-view
