### ISSUE TITLE
How to distribute Payment connectors with new commerce SDK solution

### ISSUE THREAD

**Issue by emishura** [microsoft/Dynamics365Commerce.Solutions#61]
Hello,

Please guide me on how payment connectors should be distributed with the new commerce SDK.
Before we had a separate 'PaymentExternals' folder in Retail SDK (https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/deploy-payment-connector) where we put our custom connectors. 
How to include these files in the new commerce SDK solution?

**Comment by emishura** [comment]
@madyke Hi Matt, do you have any updates regarding the distribution of payment connectors?

**Comment by madyke** [comment]
Hello @emishura - so sorry I missed this update! The bug has been fixed and you should be able to deploy payment connectors with Commerce SDK now.

I don't believe we have a dedicated payment connector sample showing how it works in Commerce SDK, but the short version is that the assemblies for the payment connector need to be included either as a part of Hardware Station extension or in CSU depending on the scenarios you want to use.

The easiest option is to probably to include them in a HWS extension by using `Content Include` to reference them from your extension project. Here is a related question around setting up payment connectors in a HWS extension, which shows some of the details:
[Unable to Copy Third Party Dll's with folder in Store Commerce Hardware Station · microsoft/Dynamics365Commerce.Solutions · Discussion #51 (github.com)](https://github.com/microsoft/Dynamics365Commerce.Solutions/discussions/51)

Here is a related question around setting up payment connectors in a CSU deployable package:
[Deploy Payment Connector with commerce SDK · microsoft/Dynamics365Commerce.Solutions · Discussion #176 (github.com)](https://github.com/microsoft/Dynamics365Commerce.Solutions/discussions/176)
