### ISSUE TITLE
POS Incorrect DataServiceEntities.g.ts file

### ISSUE THREAD

**Issue by rskandhan** [microsoft/Dynamics365Commerce.Solutions#97]
### Summary
**Describe the issue**

I created a new extended enum for new discount type (in align with the sample). This is creating incorrect DataServiceEntities.g.ts file. Because of this, our ScaleUnit project is not building. 

**Version and Error Info**

Commerce SDK Version: 9.43

Visual Studio/Visual Studio Code/MSBuild Version: Visual studio 2017

Does this happen every time the solution is built: yes

Name of Project with Error: POS

MSBuild Error: 
![image](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/31373673/58abf64e-ed1a-4780-aaad-c55fbb9955e5)

1. Create a new extended enum by following this sample: https://github.com/microsoft/Dynamics365Commerce.Solutions/blob/0206a0bcc453f6b4a06e6aab1aa61d6e32bca41c/src/PricingEngine/PricingEngine/PricingEngine/Discount/ContosoPeriodicDiscountOfferType.cs
2. Build the solution, DataServiceEntities.g.ts gets auto generated
3. The issue is with this DataServiceEntities.g.ts file.

Note: When we rename ExtensiblePeriodicDiscountOfferType to ProxyEntities.ExtensiblePeriodicDiscountOfferTypeClass (in the DataServiceEntities.g.ts file), the error gets resolved.

![image](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/31373673/72efd324-d121-4a5b-8055-d8c7fce1d310)

**Comment by madyke** [comment]
Hello @rskandhan - I have filed an internal bug on our team for this issue.

In the meantime, as a possible workaround, you can try adding this code block to the same project:
```
export class ExtensiblePeriodicDiscountOfferTypeClass extends ProxyEntities.ExtensiblePeriodicDiscountOfferTypeClass { 
} 
declare global { 
    var ExtensiblePeriodicDiscountOfferType: typeof ExtensiblePeriodicDiscountOfferTypeClass; 
} 
window.ExtensiblePeriodicDiscountOfferType = ExtensiblePeriodicDiscountOfferTypeClass; 
```

You'll need to make sure that this code is run before whatever code is trying to import `DataServiceEntities`. The easiest way to do this may be to just create an application start trigger and put it there.

**Comment by ax365** [comment]
I have the exact same issue that OP described. 
The only difference is that I've extended `ReceiptRetrievalCriteria` class.

I seem to have resolved this problem by simply creating a new `.ts` file which has the contents included in the workaround by @madyke. I've only had to accommodate it for the `ReceiptRetrievalCriteria` class instead. 

I haven't implemented an "application start trigger". 
So I'm not sure if this problem will resurface in another way. 
@madyke would you be able to provide an example of how to use the "application start trigger" for this scenario? 
I'm not familiar with these. And might end up needing to implement it after all.

**Comment by madyke** [comment]
Hi folks, so sorry I missed the update on this thread! The original bug has been fixed so the issue should not continue to resurface.

We don't have a sample of the `ApplicationStartTrigger`, but you can find a related sample for a NonCancellable trigger in these samples:
[Dynamics365Commerce.InStore/src/StoreCommerceSamples/PosExtensionSamples/Pos/Extend/Triggers at release/9.47 · microsoft/Dynamics365Commerce.InStore (github.com)](https://github.com/microsoft/Dynamics365Commerce.InStore/tree/release/9.47/src/StoreCommerceSamples/PosExtensionSamples/Pos/Extend/Triggers)
