### ISSUE TITLE
Error running install task

### ISSUE THREAD

**Issue by pkilli** [microsoft/Dynamics365Commerce.Solutions#98]
I am getting error on step 16/27 when trying to install and having UseSelfHost = true:

Microsoft.Dynamics.Commerce.Installers.Framework.Security.SetCertificatePrivateKeyPermission: Grant the user account a permission to read a certificate's private Key

GrantingReadPermission Granting account xxx a Read permission to the file C:\ProgramData\Application Data\Microsoft\Crypto\RSA\MachineKeys\xxxx representing the certificate's private key.

 StepFailedWithException [16/27] Step Microsoft.Dynamics.Commerce.Installers.Framework.Security.SetCertificatePrivateKeyPermission failed with System.InvalidOperationException: The method failed with unexpected error code 3.

when searching for the Machine key in  C:\ProgramData\Application Data\Microsoft\Crypto\RSA\MachineKeys, i notice that there are no such directory. 

The machineKey is located at C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys 

The commerce scale unit is:
10.0.32 - Commerce Scale Unit (SEALED)

**Comment by Pikhulya** [comment]
We still are unable to reproduce it in several different environments, are you still seeing the issue (if you don't apply your above workaround) with recent versions of the SDK ?

**Comment by pkilli** [comment]
I am closing this issue as i am able to build the and install
