### ISSUE TITLE
upgrding to 9.43 Public contract validation failing

### ISSUE THREAD

**Issue by Vekto** [microsoft/Dynamics365Commerce.Solutions#99]
We're receiving warnings during build in 9.43 from the added package check.

.nuget\packages\microsoft.dynamics.commerce.sdk.runtime\9.43.23118.5\build\Microsoft.Dynamics.Commerce.Sdk.Runtime.targets(62,5): warning : Error in public contract validation:
.nuget\packages\microsoft.dynamics.commerce.sdk.runtime\9.43.23118.5\build\Microsoft.Dynamics.Commerce.Sdk.Runtime.targets(62,5): warning : ReflectionOnly loading is not supported on this platform.
.nuget\packages\microsoft.dynamics.commerce.sdk.runtime\9.43.23118.5\build\Microsoft.Dynamics.Commerce.Sdk.Runtime.targets(62,5): warning :    at System.Reflection.Assembly .ReflectionOnlyLoadFrom(String assemblyFile) 
.nuget\packages\microsoft.dynamics.commerce.sdk.runtime\9.43.23118.5\build\Microsoft.Dynamics.Commerce.Sdk.Runtime.targets(62,5): warning :    at Microsoft.Dynamics.Commerce.Sdk.StoreCommerce.MSBuildTasks.CheckNonPublicContractReferencesUsage.IsPublicContract(String assemblyPath)
.nuget\packages\microsoft.dynamics.commerce.sdk.runtime\9.43.23118.5\build\Microsoft.Dynamics.Commerce.Sdk.Runtime.targets(62,5): warning :    at Microsoft.Dynamics.Commerce.Sdk.StoreCommerce.MSBuildTasks.CheckNonPublicContractReferencesUsage.Execute()

**Comment by Vekto** [comment]
reproduces in 9.48
![image](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/11138147/e52fe587-2495-428f-b451-30f54baa6d50)

**Comment by Pikhulya** [comment]
Do those warnings prevent from building the assembly ?

**Comment by Vekto** [comment]
No, Can close this ticket if you're not able to reproduce, it must be something in our environment's with one of our .net versions

**Comment by madyke** [comment]
Closing since we're unable to repro the issue.
